//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class DataLogger2 : Neo.ApplicationFramework.Tools.DataLogger.DataLogger, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.DataLogger.LogItem m_LogItem1;
		
		public DataLogger2()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.DataLogger.LogItem LogItem1
		{
			get
			{
				return this.m_LogItem1;
			}
			set
			{
				this.m_LogItem1 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			// 
			// DataLogger2
			// 
			this.Guid = new System.Guid("7f4a3ded-d990-46d4-a51f-935f4566119e");
			// 
			// LogItem1
			// 
			this.LogItem1.DatabaseFieldName = "LogItem1";
			this.LogItem1.DataSourceValue = null;
			this.LogItem1.Name = "LogItem1";
			this.LogItems.Add(this.LogItem1);
			this.SchemaVersion = ((long)(4));
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
			this.LogItem1.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("DataSourceValue", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Tensanpham"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
		}
		
		private void InitializeObjectCreations()
		{
			this.LogItem1 = new Neo.ApplicationFramework.Tools.DataLogger.LogItem();
		}
		
		private void InitializeBeginInits()
		{
		}
		
		private void InitializeEndInits()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DataLogger2));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
