//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class LCSP : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text14;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line5;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line6;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line7;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text11;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text12;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text15;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text16;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text17;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text18;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text19;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text20;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text21;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text22;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text23;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text24;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text28;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private bool m_Initialized_LCSP;
        
        public LCSP() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button3.Click += new System.EventHandler(this.m_Button3_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text15 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text15);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text16 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text16);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text17 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text17);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text18 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text18);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text19 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text19);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text20 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text20);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text21 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text21);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text22 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text22);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text23 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text23);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text24 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text24);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text28 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text28);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric8 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Rectangle3 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle4 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text14 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line5 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line6 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line7 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line8 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text11 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text12 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text15 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text16 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text17 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text18 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text19 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text20 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text21 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text22 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text23 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text24 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text28 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text16)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text17)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text18)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text19)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text20)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text21)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text22)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text23)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text24)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text28)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            this.SuspendLayout();
            // 
            // LCSP
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 224;
            this.m_Rectangle2.Left = 196;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "LCSP";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.Top = 187;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 192;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(193)))), ((int)(((byte)(217))))), System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(193)))), ((int)(((byte)(217))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Rectangle1.Height = 131;
            this.m_Rectangle1.Left = 13;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "LCSP";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.StrokeThickness = 0;
            this.m_Rectangle1.Top = 281;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 176;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "Arial";
            this.m_Button.FontSizePixels = 24;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 50;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Italic = true;
            this.m_Button.Left = 13;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "LCSP";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 28;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 94;
            this.m_Button.Top = 12;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1867409461;
            this.m_Button.Width = 100;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 57;
            this.m_Picture.Left = 709;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "LCSP";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "cvi-pharma";
            this.m_Picture.Top = 5;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 57;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontFamily = "Arial";
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 25;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "LCSP";
            this.m_Text2.Top = 88;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 85;
            // 
            // m_AnalogNumeric8
            // 
            this.m_AnalogNumeric8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric8.BlinkDynamicsValue = false;
            this.m_AnalogNumeric8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric8.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric8.EnabledDynamicsValue = true;
            this.m_AnalogNumeric8.FontFamily = "Arial";
            this.m_AnalogNumeric8.FontSizePixels = 36;
            this.m_AnalogNumeric8.Height = 67;
            this.m_AnalogNumeric8.Left = 32;
            this.m_AnalogNumeric8.MaxValue = 999999D;
            this.m_AnalogNumeric8.Name = "m_AnalogNumeric8";
            this.m_AnalogNumeric8.ScreenOwnerName = "LCSP";
            this.m_AnalogNumeric8.Top = 327;
            this.m_AnalogNumeric8.VisibleDynamicsValue = true;
            this.m_AnalogNumeric8.Width = 140;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.Bold = true;
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "Arial";
            this.m_Button1.FontSizePixels = 24;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 50;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 234;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "LCSP";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 28;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 340;
            this.m_Button1.Top = 12;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 2015808613;
            this.m_Button1.Width = 346;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.DelayMouseInputPeriod = 0;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "LCSP";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 12;
            this.m_Line.X2 = 187;
            this.m_Line.Y1 = 118;
            this.m_Line.Y2 = 118;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Arial";
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 55;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "LCSP";
            this.m_Text1.Top = 282;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 47;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.DelayMouseInputPeriod = 0;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "LCSP";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 13;
            this.m_Line1.X2 = 188;
            this.m_Line1.Y1 = 312;
            this.m_Line1.Y2 = 312;
            // 
            // m_Rectangle3
            // 
            this.m_Rectangle3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle3.BlinkDynamicsValue = false;
            this.m_Rectangle3.DelayMouseInputPeriod = 0;
            this.m_Rectangle3.EnabledDynamicsValue = true;
            this.m_Rectangle3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle3.Height = 92;
            this.m_Rectangle3.Left = 196;
            this.m_Rectangle3.Name = "m_Rectangle3";
            this.m_Rectangle3.ScreenOwnerName = "LCSP";
            this.m_Rectangle3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle3.Top = 81;
            this.m_Rectangle3.VisibleDynamicsValue = true;
            this.m_Rectangle3.Width = 573;
            // 
            // m_Rectangle4
            // 
            this.m_Rectangle4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle4.BlinkDynamicsValue = false;
            this.m_Rectangle4.DelayMouseInputPeriod = 0;
            this.m_Rectangle4.EnabledDynamicsValue = true;
            this.m_Rectangle4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle4.Height = 227;
            this.m_Rectangle4.Left = 402;
            this.m_Rectangle4.Name = "m_Rectangle4";
            this.m_Rectangle4.ScreenOwnerName = "LCSP";
            this.m_Rectangle4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle4.Top = 187;
            this.m_Rectangle4.VisibleDynamicsValue = true;
            this.m_Rectangle4.Width = 368;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Arial";
            this.m_Text.FontSizePixels = 24;
            this.m_Text.Height = 21;
            this.m_Text.Left = 313;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "LCSP";
            this.m_Text.Top = 110;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 60;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontFamily = "Arial";
            this.m_Text5.FontSizePixels = 20;
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 415;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "LCSP";
            this.m_Text5.Top = 246;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 78;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.DelayMouseInputPeriod = 0;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontFamily = "Arial";
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Height = 21;
            this.m_Text6.Left = 414;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "LCSP";
            this.m_Text6.Top = 289;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 80;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.DelayMouseInputPeriod = 0;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontFamily = "Arial";
            this.m_Text8.FontSizePixels = 20;
            this.m_Text8.Height = 21;
            this.m_Text8.Left = 416;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "LCSP";
            this.m_Text8.Top = 379;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 81;
            // 
            // m_Text13
            // 
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.DelayMouseInputPeriod = 0;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontFamily = "Arial";
            this.m_Text13.FontSizePixels = 20;
            this.m_Text13.Height = 21;
            this.m_Text13.Left = 416;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.ScreenOwnerName = "LCSP";
            this.m_Text13.Top = 336;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 78;
            // 
            // m_Text14
            // 
            this.m_Text14.BlinkDynamicsValue = false;
            this.m_Text14.Bold = true;
            this.m_Text14.DelayMouseInputPeriod = 0;
            this.m_Text14.EnabledDynamicsValue = true;
            this.m_Text14.FontFamily = "Arial";
            this.m_Text14.FontSizePixels = 20;
            this.m_Text14.Height = 21;
            this.m_Text14.Italic = true;
            this.m_Text14.Left = 439;
            this.m_Text14.Name = "m_Text14";
            this.m_Text14.ScreenOwnerName = "LCSP";
            this.m_Text14.Top = 199;
            this.m_Text14.VisibleDynamicsValue = true;
            this.m_Text14.Width = 54;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontFamily = "Arial";
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 34;
            this.m_Text4.Italic = true;
            this.m_Text4.Left = 574;
            this.m_Text4.MultiLine = true;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "LCSP";
            this.m_Text4.TextHorizontalAlignment = "Center";
            this.m_Text4.TextVerticalAlignment = "Center";
            this.m_Text4.Top = 187;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 48;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.Bold = true;
            this.m_Text7.DelayMouseInputPeriod = 0;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontFamily = "Arial";
            this.m_Text7.FontSizePixels = 20;
            this.m_Text7.Height = 34;
            this.m_Text7.Italic = true;
            this.m_Text7.Left = 669;
            this.m_Text7.MultiLine = true;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.ScreenOwnerName = "LCSP";
            this.m_Text7.TextHorizontalAlignment = "Center";
            this.m_Text7.TextVerticalAlignment = "Center";
            this.m_Text7.Top = 187;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 52;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.DelayMouseInputPeriod = 0;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "LCSP";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 769;
            this.m_Line2.X2 = 403;
            this.m_Line2.Y1 = 241;
            this.m_Line2.Y2 = 241;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.DelayMouseInputPeriod = 0;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "LCSP";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 769;
            this.m_Line3.X2 = 403;
            this.m_Line3.Y1 = 280;
            this.m_Line3.Y2 = 280;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.DelayMouseInputPeriod = 0;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "LCSP";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 770;
            this.m_Line4.X2 = 404;
            this.m_Line4.Y1 = 329;
            this.m_Line4.Y2 = 329;
            // 
            // m_Line5
            // 
            this.m_Line5.BlinkDynamicsValue = false;
            this.m_Line5.DelayMouseInputPeriod = 0;
            this.m_Line5.EnabledDynamicsValue = true;
            this.m_Line5.Fill = null;
            this.m_Line5.Name = "m_Line5";
            this.m_Line5.ScreenOwnerName = "LCSP";
            this.m_Line5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line5.VisibleDynamicsValue = true;
            this.m_Line5.X1 = 404;
            this.m_Line5.X2 = 769;
            this.m_Line5.Y1 = 374;
            this.m_Line5.Y2 = 374;
            // 
            // m_Line6
            // 
            this.m_Line6.BlinkDynamicsValue = false;
            this.m_Line6.DelayMouseInputPeriod = 0;
            this.m_Line6.EnabledDynamicsValue = true;
            this.m_Line6.Fill = null;
            this.m_Line6.Name = "m_Line6";
            this.m_Line6.ScreenOwnerName = "LCSP";
            this.m_Line6.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line6.VisibleDynamicsValue = true;
            this.m_Line6.X1 = 569;
            this.m_Line6.X2 = 569;
            this.m_Line6.Y1 = 187;
            this.m_Line6.Y2 = 413;
            // 
            // m_Line7
            // 
            this.m_Line7.BlinkDynamicsValue = false;
            this.m_Line7.DelayMouseInputPeriod = 0;
            this.m_Line7.EnabledDynamicsValue = true;
            this.m_Line7.Fill = null;
            this.m_Line7.Name = "m_Line7";
            this.m_Line7.ScreenOwnerName = "LCSP";
            this.m_Line7.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line7.VisibleDynamicsValue = true;
            this.m_Line7.X1 = 672;
            this.m_Line7.X2 = 672;
            this.m_Line7.Y1 = 187;
            this.m_Line7.Y2 = 413;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.Bold = true;
            this.m_Text9.DelayMouseInputPeriod = 0;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontFamily = "Arial";
            this.m_Text9.FontSizePixels = 20;
            this.m_Text9.Height = 34;
            this.m_Text9.Italic = true;
            this.m_Text9.Left = 216;
            this.m_Text9.MultiLine = true;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "LCSP";
            this.m_Text9.TextHorizontalAlignment = "Center";
            this.m_Text9.TextVerticalAlignment = "Center";
            this.m_Text9.Top = 186;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 83;
            // 
            // m_Line8
            // 
            this.m_Line8.BlinkDynamicsValue = false;
            this.m_Line8.DelayMouseInputPeriod = 0;
            this.m_Line8.EnabledDynamicsValue = true;
            this.m_Line8.Fill = null;
            this.m_Line8.Name = "m_Line8";
            this.m_Line8.ScreenOwnerName = "LCSP";
            this.m_Line8.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line8.StrokeThickness = 2;
            this.m_Line8.VisibleDynamicsValue = true;
            this.m_Line8.X1 = 388;
            this.m_Line8.X2 = 195;
            this.m_Line8.Y1 = 240;
            this.m_Line8.Y2 = 240;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(188)))), ((int)(((byte)(214))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.Bold = true;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.DelayMouseInputPeriod = 0;
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontFamily = "Arial";
            this.m_Button3.FontSizePixels = 28;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Height = 185;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 13;
            this.m_Button3.MultiLine = true;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "LCSP";
            this.m_Button3.StyleName = "Glossy";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button3.TextHeight = 66;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 169;
            this.m_Button3.Top = 81;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = -491118820;
            this.m_Button3.Width = 175;
            // 
            // m_Text11
            // 
            this.m_Text11.AutoSize = false;
            this.m_Text11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text11.BlinkDynamicsValue = false;
            this.m_Text11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text11.DelayMouseInputPeriod = 0;
            this.m_Text11.EnabledDynamicsValue = true;
            this.m_Text11.FontSizePixels = 20;
            this.m_Text11.Height = 34;
            this.m_Text11.Left = 583;
            this.m_Text11.Name = "m_Text11";
            this.m_Text11.ScreenOwnerName = "LCSP";
            this.m_Text11.TextHorizontalAlignment = "Center";
            this.m_Text11.TextVerticalAlignment = "Center";
            this.m_Text11.Top = 243;
            this.m_Text11.VisibleDynamicsValue = true;
            this.m_Text11.Width = 80;
            // 
            // m_Text12
            // 
            this.m_Text12.AutoSize = false;
            this.m_Text12.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text12.BlinkDynamicsValue = false;
            this.m_Text12.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text12.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text12.DelayMouseInputPeriod = 0;
            this.m_Text12.EnabledDynamicsValue = true;
            this.m_Text12.FontSizePixels = 20;
            this.m_Text12.Height = 34;
            this.m_Text12.Left = 583;
            this.m_Text12.Name = "m_Text12";
            this.m_Text12.ScreenOwnerName = "LCSP";
            this.m_Text12.TextHorizontalAlignment = "Center";
            this.m_Text12.TextVerticalAlignment = "Center";
            this.m_Text12.Top = 287;
            this.m_Text12.VisibleDynamicsValue = true;
            this.m_Text12.Width = 80;
            // 
            // m_Text15
            // 
            this.m_Text15.AutoSize = false;
            this.m_Text15.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text15.BlinkDynamicsValue = false;
            this.m_Text15.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text15.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text15.DelayMouseInputPeriod = 0;
            this.m_Text15.EnabledDynamicsValue = true;
            this.m_Text15.FontSizePixels = 20;
            this.m_Text15.Height = 34;
            this.m_Text15.Left = 583;
            this.m_Text15.Name = "m_Text15";
            this.m_Text15.ScreenOwnerName = "LCSP";
            this.m_Text15.TextHorizontalAlignment = "Center";
            this.m_Text15.TextVerticalAlignment = "Center";
            this.m_Text15.Top = 334;
            this.m_Text15.VisibleDynamicsValue = true;
            this.m_Text15.Width = 80;
            // 
            // m_Text16
            // 
            this.m_Text16.AutoSize = false;
            this.m_Text16.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text16.BlinkDynamicsValue = false;
            this.m_Text16.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text16.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text16.DelayMouseInputPeriod = 0;
            this.m_Text16.EnabledDynamicsValue = true;
            this.m_Text16.FontSizePixels = 20;
            this.m_Text16.Height = 34;
            this.m_Text16.Left = 583;
            this.m_Text16.Name = "m_Text16";
            this.m_Text16.ScreenOwnerName = "LCSP";
            this.m_Text16.TextHorizontalAlignment = "Center";
            this.m_Text16.TextVerticalAlignment = "Center";
            this.m_Text16.Top = 377;
            this.m_Text16.VisibleDynamicsValue = true;
            this.m_Text16.Width = 80;
            // 
            // m_Text10
            // 
            this.m_Text10.AutoSize = false;
            this.m_Text10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text10.DelayMouseInputPeriod = 0;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontSizePixels = 20;
            this.m_Text10.Height = 34;
            this.m_Text10.Left = 583;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.ScreenOwnerName = "LCSP";
            this.m_Text10.TextHorizontalAlignment = "Center";
            this.m_Text10.TextVerticalAlignment = "Center";
            this.m_Text10.Top = 243;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 80;
            // 
            // m_Text17
            // 
            this.m_Text17.AutoSize = false;
            this.m_Text17.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text17.BlinkDynamicsValue = false;
            this.m_Text17.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text17.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text17.DelayMouseInputPeriod = 0;
            this.m_Text17.EnabledDynamicsValue = true;
            this.m_Text17.FontSizePixels = 20;
            this.m_Text17.Height = 34;
            this.m_Text17.Left = 583;
            this.m_Text17.Name = "m_Text17";
            this.m_Text17.ScreenOwnerName = "LCSP";
            this.m_Text17.TextHorizontalAlignment = "Center";
            this.m_Text17.TextVerticalAlignment = "Center";
            this.m_Text17.Top = 287;
            this.m_Text17.VisibleDynamicsValue = true;
            this.m_Text17.Width = 80;
            // 
            // m_Text18
            // 
            this.m_Text18.AutoSize = false;
            this.m_Text18.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text18.BlinkDynamicsValue = false;
            this.m_Text18.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text18.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text18.DelayMouseInputPeriod = 0;
            this.m_Text18.EnabledDynamicsValue = true;
            this.m_Text18.FontSizePixels = 20;
            this.m_Text18.Height = 34;
            this.m_Text18.Left = 583;
            this.m_Text18.Name = "m_Text18";
            this.m_Text18.ScreenOwnerName = "LCSP";
            this.m_Text18.TextHorizontalAlignment = "Center";
            this.m_Text18.TextVerticalAlignment = "Center";
            this.m_Text18.Top = 334;
            this.m_Text18.VisibleDynamicsValue = true;
            this.m_Text18.Width = 80;
            // 
            // m_Text19
            // 
            this.m_Text19.AutoSize = false;
            this.m_Text19.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text19.BlinkDynamicsValue = false;
            this.m_Text19.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text19.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text19.DelayMouseInputPeriod = 0;
            this.m_Text19.EnabledDynamicsValue = true;
            this.m_Text19.FontSizePixels = 20;
            this.m_Text19.Height = 34;
            this.m_Text19.Left = 583;
            this.m_Text19.Name = "m_Text19";
            this.m_Text19.ScreenOwnerName = "LCSP";
            this.m_Text19.TextHorizontalAlignment = "Center";
            this.m_Text19.TextVerticalAlignment = "Center";
            this.m_Text19.Top = 377;
            this.m_Text19.VisibleDynamicsValue = true;
            this.m_Text19.Width = 80;
            // 
            // m_Text20
            // 
            this.m_Text20.AutoSize = false;
            this.m_Text20.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text20.BlinkDynamicsValue = false;
            this.m_Text20.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text20.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text20.DelayMouseInputPeriod = 0;
            this.m_Text20.EnabledDynamicsValue = true;
            this.m_Text20.FontSizePixels = 20;
            this.m_Text20.Height = 34;
            this.m_Text20.Left = 680;
            this.m_Text20.Name = "m_Text20";
            this.m_Text20.ScreenOwnerName = "LCSP";
            this.m_Text20.TextHorizontalAlignment = "Center";
            this.m_Text20.TextVerticalAlignment = "Center";
            this.m_Text20.Top = 243;
            this.m_Text20.VisibleDynamicsValue = true;
            this.m_Text20.Width = 80;
            // 
            // m_Text21
            // 
            this.m_Text21.AutoSize = false;
            this.m_Text21.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text21.BlinkDynamicsValue = false;
            this.m_Text21.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text21.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text21.DelayMouseInputPeriod = 0;
            this.m_Text21.EnabledDynamicsValue = true;
            this.m_Text21.FontSizePixels = 20;
            this.m_Text21.Height = 34;
            this.m_Text21.Left = 680;
            this.m_Text21.Name = "m_Text21";
            this.m_Text21.ScreenOwnerName = "LCSP";
            this.m_Text21.TextHorizontalAlignment = "Center";
            this.m_Text21.TextVerticalAlignment = "Center";
            this.m_Text21.Top = 287;
            this.m_Text21.VisibleDynamicsValue = true;
            this.m_Text21.Width = 80;
            // 
            // m_Text22
            // 
            this.m_Text22.AutoSize = false;
            this.m_Text22.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text22.BlinkDynamicsValue = false;
            this.m_Text22.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text22.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text22.DelayMouseInputPeriod = 0;
            this.m_Text22.EnabledDynamicsValue = true;
            this.m_Text22.FontSizePixels = 20;
            this.m_Text22.Height = 34;
            this.m_Text22.Left = 680;
            this.m_Text22.Name = "m_Text22";
            this.m_Text22.ScreenOwnerName = "LCSP";
            this.m_Text22.TextHorizontalAlignment = "Center";
            this.m_Text22.TextVerticalAlignment = "Center";
            this.m_Text22.Top = 334;
            this.m_Text22.VisibleDynamicsValue = true;
            this.m_Text22.Width = 80;
            // 
            // m_Text23
            // 
            this.m_Text23.AutoSize = false;
            this.m_Text23.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text23.BlinkDynamicsValue = false;
            this.m_Text23.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text23.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Text23.DelayMouseInputPeriod = 0;
            this.m_Text23.EnabledDynamicsValue = true;
            this.m_Text23.FontSizePixels = 20;
            this.m_Text23.Height = 34;
            this.m_Text23.Left = 680;
            this.m_Text23.Name = "m_Text23";
            this.m_Text23.ScreenOwnerName = "LCSP";
            this.m_Text23.TextHorizontalAlignment = "Center";
            this.m_Text23.TextVerticalAlignment = "Center";
            this.m_Text23.Top = 377;
            this.m_Text23.VisibleDynamicsValue = true;
            this.m_Text23.Width = 80;
            // 
            // m_Text24
            // 
            this.m_Text24.AutoSize = false;
            this.m_Text24.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(193)))), ((int)(((byte)(217))))), System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(193)))), ((int)(((byte)(217))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Text24.BlinkDynamicsValue = false;
            this.m_Text24.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text24.DelayMouseInputPeriod = 0;
            this.m_Text24.EnabledDynamicsValue = true;
            this.m_Text24.FontSizePixels = 48;
            this.m_Text24.Height = 107;
            this.m_Text24.Left = 225;
            this.m_Text24.Name = "m_Text24";
            this.m_Text24.ScreenOwnerName = "LCSP";
            this.m_Text24.TextHorizontalAlignment = "Center";
            this.m_Text24.TextVerticalAlignment = "Center";
            this.m_Text24.Top = 275;
            this.m_Text24.VisibleDynamicsValue = true;
            this.m_Text24.Width = 138;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.Bold = true;
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "Arial";
            this.m_Button4.FontSizePixels = 24;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button4.Height = 50;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 234;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "LCSP";
            this.m_Button4.StyleName = "Glossy";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button4.TextHeight = 28;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 340;
            this.m_Button4.Top = 12;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 2015808613;
            this.m_Button4.Width = 346;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.Bold = true;
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button5.DelayMouseInputPeriod = 0;
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontFamily = "Arial";
            this.m_Button5.FontSizePixels = 24;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button5.Height = 50;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 234;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "LCSP";
            this.m_Button5.StyleName = "Glossy";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button5.TextHeight = 28;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 340;
            this.m_Button5.Top = 422;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = 2015808613;
            this.m_Button5.Width = 346;
            // 
            // m_Text28
            // 
            this.m_Text28.BlinkDynamicsValue = false;
            this.m_Text28.DelayMouseInputPeriod = 0;
            this.m_Text28.EnabledDynamicsValue = true;
            this.m_Text28.FontFamily = "Arial";
            this.m_Text28.FontSizePixels = 22;
            this.m_Text28.Height = 21;
            this.m_Text28.Left = 583;
            this.m_Text28.Name = "m_Text28";
            this.m_Text28.ScreenOwnerName = "LCSP";
            this.m_Text28.Top = 21;
            this.m_Text28.VisibleDynamicsValue = true;
            this.m_Text28.Width = 29;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontFamily = "Arial";
            this.m_Text3.FontSizePixels = 26;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 479;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "LCSP";
            this.m_Text3.Top = 108;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 28;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "LCSP";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_LCSP = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_LCSP) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric8);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Rectangle3);
            this.DrawingPrimitives.Add(this.m_Rectangle4);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Text14);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_Line5);
            this.DrawingPrimitives.Add(this.m_Line6);
            this.DrawingPrimitives.Add(this.m_Line7);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Line8);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Text11);
            this.DrawingPrimitives.Add(this.m_Text12);
            this.DrawingPrimitives.Add(this.m_Text15);
            this.DrawingPrimitives.Add(this.m_Text16);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_Text17);
            this.DrawingPrimitives.Add(this.m_Text18);
            this.DrawingPrimitives.Add(this.m_Text19);
            this.DrawingPrimitives.Add(this.m_Text20);
            this.DrawingPrimitives.Add(this.m_Text21);
            this.DrawingPrimitives.Add(this.m_Text22);
            this.DrawingPrimitives.Add(this.m_Text23);
            this.DrawingPrimitives.Add(this.m_Text24);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Text28);
            this.DrawingPrimitives.Add(this.m_Text3);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text16)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text17)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text18)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text19)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text20)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text21)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text22)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text23)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text24)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text28)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
        }
        
        private void m_Button3_Action_Click(object sender, System.EventArgs e) {
            string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Load);
            if (string.IsNullOrEmpty(recipeFieldName)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.Recipe1.LoadRecipe(recipeFieldName);
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Show Screen", "OPERATE_2", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.OPERATE_2.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(LCSP));
            this.m_Button.Text = resources.GetText("LCSP.Button.Text", "Trở lại");
            this.m_Text2.Text = resources.GetText("LCSP.Text2.Text", "Chọn Sản phẩm");
            this.m_Button1.Text = resources.GetText("LCSP.Button1.Text", "CHỌN SẢN PHẨM");
            this.m_Text1.Text = resources.GetText("LCSP.Text1.Text", "Số lô SX");
            this.m_Text.Text = resources.GetText("LCSP.Text.Text", "Sản phẩm:");
            this.m_Text5.Text = resources.GetText("LCSP.Text5.Text", "Trạm hàn trên");
            this.m_Text6.Text = resources.GetText("LCSP.Text6.Text", "Trạm hàn dưới");
            this.m_Text8.Text = resources.GetText("LCSP.Text8.Text", "Trạm hàn số lô");
            this.m_Text13.Text = resources.GetText("LCSP.Text13.Text", "Trạm hàn Seal");
            this.m_Text14.Text = resources.GetText("LCSP.Text14.Text", "Trạm hàn");
            this.m_Text4.Text = resources.GetText("LCSP.Text4.Text", "Nhiệt độ \r\ncài đặt");
            this.m_Text7.Text = resources.GetText("LCSP.Text7.Text", "Nhiệt độ \r\ncảnh báo");
            this.m_Text9.Text = resources.GetText("LCSP.Text9.Text", "Độ dài \r\nbước kéo (mm)");
            this.m_Button3.Text = resources.GetText("LCSP.Button3.Text", "Chọn \r\nsản phẩm");
            this.m_Button4.Text = resources.GetText("LCSP.Button4.Text", "CHỌN SẢN PHẨM");
            this.m_Button5.Text = resources.GetText("LCSP.Button5.Text", "ĐIỀU KHIỂN THIẾT BỊ");
            this.m_Text28.Text = resources.GetText("LCSP.Text28.Text", "User");
            this.m_Text3.Text = resources.GetText("LCSP.Text3.Text", "Text");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_LCSP) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Solosanpham"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric8.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tram_han_tren"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text11.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanduoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text12.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSeal"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text15.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSolo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text16.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tram_han_tren"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text10.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanduoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text17.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSeal"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text18.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSolo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text19.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Canhbaotren"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text20.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Canhbaoduoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text21.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CanhbaoSeal"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text22.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CanhbaoSolo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text23.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_DoDaiBuocKeo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text24.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding15 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text28.DataBindings.Add(dynamicBinding15);
            this.m_DynamicBindings.Add(dynamicBinding15);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding16 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagLatestLoadedRecipeName"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text3.DataBindings.Add(dynamicBinding16);
            this.m_DynamicBindings.Add(dynamicBinding16);
        }
    }
}
