//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class REPORT : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.TouchComboBox.TouchComboBoxHostCF m_TouchComboBox1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text28;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line5;
        
        private bool m_Initialized_REPORT;
        
        public REPORT() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_TouchComboBox1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.m_TouchComboBox1_Action_MouseDown);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TouchComboBoxCFAdapter TouchComboBox1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TouchComboBoxCFAdapter>(this.m_TouchComboBox1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text28 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text28);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line5);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_TouchComboBox1 = new Neo.ApplicationFramework.Controls.TouchComboBox.TouchComboBoxHostCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric8 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text28 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line5 = new Neo.ApplicationFramework.Controls.Controls.Line();
            ((System.ComponentModel.ISupportInitialize)(this.m_TouchComboBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text28)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            this.SuspendLayout();
            // 
            // REPORT
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_TouchComboBox1
            // 
            this.m_TouchComboBox1.AlternateBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(161)))), ((int)(((byte)(161))))), System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(107)))), ((int)(((byte)(107))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_TouchComboBox1.AlternateForeground = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(232)))), ((int)(((byte)(232)))));
            this.m_TouchComboBox1.ArrowBoxWidth = 30;
            this.m_TouchComboBox1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TouchComboBox1.BlinkDynamicsValue = false;
            this.m_TouchComboBox1.BorderColor = System.Drawing.SystemColors.WindowFrame;
            this.m_TouchComboBox1.BorderThickness = 1;
            this.m_TouchComboBox1.DelayLoad = false;
            this.m_TouchComboBox1.EnabledDynamicsValue = true;
            this.m_TouchComboBox1.FontName = "Arial";
            this.m_TouchComboBox1.FontSize = 20D;
            this.m_TouchComboBox1.Foreground = System.Drawing.Color.Black;
            stringintervalmappercf1.DefaultValue = null;
            stringintervalcf1.Value = "A";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "B";
            stringintervalcf3.End = 2D;
            stringintervalcf3.Start = 2D;
            stringintervalcf3.Value = "C";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            stringintervalmappercf1.Intervals.Add(stringintervalcf3);
            this.m_TouchComboBox1.IntervalMapper = stringintervalmappercf1;
            this.m_TouchComboBox1.IsSeparatorVisible = true;
            this.m_TouchComboBox1.ItemHeight = 30;
            this.m_TouchComboBox1.Location = new System.Drawing.Point(427, 112);
            this.m_TouchComboBox1.Name = "m_TouchComboBox1";
            this.m_TouchComboBox1.ScrollBarWidth = 20;
            this.m_TouchComboBox1.SelectedBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(136)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TouchComboBox1.SelectedForeground = System.Drawing.Color.White;
            this.m_TouchComboBox1.SelectedItem = null;
            this.m_TouchComboBox1.SeparatorColor = System.Drawing.Color.White;
            this.m_TouchComboBox1.Size = new System.Drawing.Size(166, 37);
            this.m_TouchComboBox1.TabIndex = 2147483647;
            this.m_TouchComboBox1.TouchScrollSensitivity = 8;
            this.m_TouchComboBox1.VisibleDynamicsValue = true;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(1, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(162)))), ((int)(((byte)(198))))), System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(162)))), ((int)(((byte)(198))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Rectangle.Height = 292;
            this.m_Rectangle.Left = 172;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "REPORT";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.StrokeThickness = 0;
            this.m_Rectangle.Top = 94;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 441;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "Arial";
            this.m_Button.FontSizePixels = 20;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 51;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Italic = true;
            this.m_Button.Left = 11;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "REPORT";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 24;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 94;
            this.m_Button.Top = 10;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1179089179;
            this.m_Button.Width = 100;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 60;
            this.m_Picture.Left = 718;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "REPORT";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "cvi-pharma";
            this.m_Picture.Top = 3;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 60;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontFamily = "Arial";
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 194;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "REPORT";
            this.m_Text2.Top = 116;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 78;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontFamily = "Arial";
            this.m_Text3.FontSizePixels = 20;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 194;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "REPORT";
            this.m_Text3.Top = 159;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 51;
            // 
            // m_AnalogNumeric8
            // 
            this.m_AnalogNumeric8.BlinkDynamicsValue = false;
            this.m_AnalogNumeric8.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric8.EnabledDynamicsValue = true;
            this.m_AnalogNumeric8.FontSizePixels = 20;
            this.m_AnalogNumeric8.Height = 34;
            this.m_AnalogNumeric8.Left = 427;
            this.m_AnalogNumeric8.MaxValue = 999999D;
            this.m_AnalogNumeric8.MinValue = 10119D;
            this.m_AnalogNumeric8.Name = "m_AnalogNumeric8";
            this.m_AnalogNumeric8.ScreenOwnerName = "REPORT";
            this.m_AnalogNumeric8.Top = 157;
            this.m_AnalogNumeric8.ValidateValueOnInput = true;
            this.m_AnalogNumeric8.VisibleDynamicsValue = true;
            this.m_AnalogNumeric8.Width = 166;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontFamily = "Arial";
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 194;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "REPORT";
            this.m_Text4.Top = 202;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 52;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 20;
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 441;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "REPORT";
            this.m_Text5.Top = 204;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 77;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.DelayMouseInputPeriod = 0;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontFamily = "Arial";
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Height = 21;
            this.m_Text6.Left = 194;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "REPORT";
            this.m_Text6.Top = 245;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 116;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 34;
            this.m_AnalogNumeric.Left = 427;
            this.m_AnalogNumeric.MaxValue = 999999D;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ScreenOwnerName = "REPORT";
            this.m_AnalogNumeric.Top = 243;
            this.m_AnalogNumeric.ValidateValueOnInput = true;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 166;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.DelayMouseInputPeriod = 0;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontFamily = "Arial";
            this.m_Text7.FontSizePixels = 20;
            this.m_Text7.Height = 21;
            this.m_Text7.Left = 194;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.ScreenOwnerName = "REPORT";
            this.m_Text7.Top = 288;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 94;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 34;
            this.m_AnalogNumeric1.Left = 427;
            this.m_AnalogNumeric1.MaxValue = 999999D;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.ScreenOwnerName = "REPORT";
            this.m_AnalogNumeric1.Top = 286;
            this.m_AnalogNumeric1.ValidateValueOnInput = true;
            this.m_AnalogNumeric1.VisibleDynamicsValue = true;
            this.m_AnalogNumeric1.Width = 166;
            // 
            // m_Text9
            // 
            this.m_Text9.AutoSize = false;
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.DelayMouseInputPeriod = 0;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontFamily = "Arial";
            this.m_Text9.FontSizePixels = 20;
            this.m_Text9.Height = 30;
            this.m_Text9.Left = 194;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "REPORT";
            this.m_Text9.Top = 333;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 201;
            // 
            // m_Text10
            // 
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.DelayMouseInputPeriod = 0;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontFamily = "Arial";
            this.m_Text10.FontSizePixels = 20;
            this.m_Text10.Height = 21;
            this.m_Text10.Left = 445;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.ScreenOwnerName = "REPORT";
            this.m_Text10.Top = 338;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 68;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.Bold = true;
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "Arial";
            this.m_Button1.FontSizePixels = 28;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 51;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 221;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "REPORT";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 33;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 353;
            this.m_Button1.Top = 10;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -892524529;
            this.m_Button1.Width = 359;
            // 
            // m_Text28
            // 
            this.m_Text28.BlinkDynamicsValue = false;
            this.m_Text28.DelayMouseInputPeriod = 0;
            this.m_Text28.EnabledDynamicsValue = true;
            this.m_Text28.FontFamily = "Arial";
            this.m_Text28.FontSizePixels = 22;
            this.m_Text28.Height = 21;
            this.m_Text28.Left = 595;
            this.m_Text28.Name = "m_Text28";
            this.m_Text28.ScreenOwnerName = "REPORT";
            this.m_Text28.Top = 19;
            this.m_Text28.VisibleDynamicsValue = true;
            this.m_Text28.Width = 29;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontFamily = "Arial";
            this.m_Button2.FontSizePixels = 24;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button2.Height = 51;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 349;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "REPORT";
            this.m_Button2.StyleName = "Glossy";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button2.TextHeight = 28;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 94;
            this.m_Button2.Top = 404;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -1179089179;
            this.m_Button2.Width = 100;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.DelayMouseInputPeriod = 0;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "REPORT";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 172;
            this.m_Line.X2 = 612;
            this.m_Line.Y1 = 153;
            this.m_Line.Y2 = 153;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.DelayMouseInputPeriod = 0;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "REPORT";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 174;
            this.m_Line1.X2 = 612;
            this.m_Line1.Y1 = 195;
            this.m_Line1.Y2 = 195;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.DelayMouseInputPeriod = 0;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "REPORT";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 172;
            this.m_Line2.X2 = 612;
            this.m_Line2.Y1 = 241;
            this.m_Line2.Y2 = 241;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.DelayMouseInputPeriod = 0;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "REPORT";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 173;
            this.m_Line3.X2 = 611;
            this.m_Line3.Y1 = 285;
            this.m_Line3.Y2 = 284;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.DelayMouseInputPeriod = 0;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "REPORT";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 172;
            this.m_Line4.X2 = 612;
            this.m_Line4.Y1 = 332;
            this.m_Line4.Y2 = 332;
            // 
            // m_Line5
            // 
            this.m_Line5.BlinkDynamicsValue = false;
            this.m_Line5.DelayMouseInputPeriod = 0;
            this.m_Line5.EnabledDynamicsValue = true;
            this.m_Line5.Fill = null;
            this.m_Line5.Name = "m_Line5";
            this.m_Line5.ScreenOwnerName = "REPORT";
            this.m_Line5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line5.VisibleDynamicsValue = true;
            this.m_Line5.X1 = 399;
            this.m_Line5.X2 = 399;
            this.m_Line5.Y1 = 94;
            this.m_Line5.Y2 = 384;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "REPORT";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_REPORT = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_REPORT) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_TouchComboBox1);
            ((System.ComponentModel.ISupportInitialize)(this.m_TouchComboBox1)).EndInit();
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric8);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Text28);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_Line5);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text28)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
        }
        
        private void m_TouchComboBox1_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.Tags.Tensanpham.SetString("");
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
            Neo.ApplicationFramework.Generated.Globals.Reports.GenerateReport(Neo.ApplicationFramework.Interfaces.Reporting.GenerateReportAction.Save, "Report1", Neo.ApplicationFramework.Interfaces.FileDirectory.ProjectFiles, "");
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(REPORT));
            this.m_Button.Text = resources.GetText("REPORT.Button.Text", "Trở lại");
            this.m_Text2.Text = resources.GetText("REPORT.Text2.Text", "Mã Sản phẩm:");
            this.m_Text3.Text = resources.GetText("REPORT.Text3.Text", "Số lô SX:");
            this.m_Text4.Text = resources.GetText("REPORT.Text4.Text", "Ngày SX:");
            this.m_Text5.Text = resources.GetText("REPORT.Text5.Text", "Date and time");
            this.m_Text6.Text = resources.GetText("REPORT.Text6.Text", "Khối lượng sản phẩm:");
            this.m_Text7.Text = resources.GetText("REPORT.Text7.Text", "Khối lượng SP lỗi:");
            this.m_Text9.Text = resources.GetText("REPORT.Text9.Text", "Nhân viên vận hành:");
            this.m_Text10.Text = resources.GetText("REPORT.Text10.Text", "Current user ");
            this.m_Button1.Text = resources.GetText("REPORT.Button1.Text", "BÁO CÁO CA VẬN HÀNH");
            this.m_Text28.Text = resources.GetText("REPORT.Text28.Text", "User");
            this.m_Button2.Text = resources.GetText("REPORT.Button2.Text", "Lưu lại");
            resources.ApplyTexts(this.m_TouchComboBox1, "Texts", "REPORT.TouchComboBox1.Texts[0]", "A", "REPORT.TouchComboBox1.Texts[1]", "B", "REPORT.TouchComboBox1.Texts[2]", "C");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_REPORT) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Masanpham"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_TouchComboBox1.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Solosanpham"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric8.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_NgaySX"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text5.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.sosanpham"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SoViLoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text10.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text28.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
        }
    }
}
