//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class SETUP : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text14;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric3;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric4;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric5;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric6;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line5;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.TextBox m_SanPham;
        
        private Neo.ApplicationFramework.Controls.Controls.TextBox m_MaSanPham;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line7;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric8;
        
        private bool m_Initialized_SETUP;
        
        public SETUP() {
            this.InitializeComponent();
            this.Adapter.Opened += new System.EventHandler(this.SETUP_Opened);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_AnalogNumeric.GotFocus += new System.EventHandler(this.m_AnalogNumeric_Action_GotFocus);
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter SanPham {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter>(this.m_SanPham);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter MaSanPham {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter>(this.m_MaSanPham);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric8);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text14 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric2 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric3 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric4 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric5 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric6 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric7 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line5 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line6 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_SanPham = new Neo.ApplicationFramework.Controls.Controls.TextBox();
            this.m_MaSanPham = new Neo.ApplicationFramework.Controls.Controls.TextBox();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line7 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_AnalogNumeric8 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_SanPham)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MaSanPham)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).BeginInit();
            this.SuspendLayout();
            // 
            // SETUP
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 224;
            this.m_Rectangle2.Left = 49;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "SETUP";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.Top = 233;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 192;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 124;
            this.m_Rectangle1.Left = 136;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "SETUP";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle1.Top = 82;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 496;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.UpperLeft);
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 227;
            this.m_Rectangle.Left = 255;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "SETUP";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = 233;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 368;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 26;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 50;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Italic = true;
            this.m_Button.Left = 6;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "SETUP";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 31;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 94;
            this.m_Button.Top = 9;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1887562421;
            this.m_Button.Width = 100;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 60;
            this.m_Picture.Left = 718;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "SETUP";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "cvi-pharma";
            this.m_Picture.Top = 3;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 60;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Arial";
            this.m_Text1.FontSizePixels = 24;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 194;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "SETUP";
            this.m_Text1.Top = 112;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 82;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontFamily = "Arial";
            this.m_Text2.FontSizePixels = 24;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 194;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "SETUP";
            this.m_Text2.Top = 155;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 78;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontFamily = "Arial";
            this.m_Text5.FontSizePixels = 20;
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 268;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "SETUP";
            this.m_Text5.Top = 292;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 78;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.DelayMouseInputPeriod = 0;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontFamily = "Arial";
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Height = 21;
            this.m_Text6.Left = 267;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "SETUP";
            this.m_Text6.Top = 335;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 80;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.DelayMouseInputPeriod = 0;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontFamily = "Arial";
            this.m_Text8.FontSizePixels = 20;
            this.m_Text8.Height = 21;
            this.m_Text8.Left = 269;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "SETUP";
            this.m_Text8.Top = 425;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 81;
            // 
            // m_Text13
            // 
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.DelayMouseInputPeriod = 0;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontFamily = "Arial";
            this.m_Text13.FontSizePixels = 20;
            this.m_Text13.Height = 21;
            this.m_Text13.Left = 269;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.ScreenOwnerName = "SETUP";
            this.m_Text13.Top = 382;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 78;
            // 
            // m_Text14
            // 
            this.m_Text14.BlinkDynamicsValue = false;
            this.m_Text14.Bold = true;
            this.m_Text14.DelayMouseInputPeriod = 0;
            this.m_Text14.EnabledDynamicsValue = true;
            this.m_Text14.FontFamily = "Arial";
            this.m_Text14.FontSizePixels = 20;
            this.m_Text14.Height = 21;
            this.m_Text14.Italic = true;
            this.m_Text14.Left = 292;
            this.m_Text14.Name = "m_Text14";
            this.m_Text14.ScreenOwnerName = "SETUP";
            this.m_Text14.Top = 245;
            this.m_Text14.VisibleDynamicsValue = true;
            this.m_Text14.Width = 54;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontFamily = "Arial";
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 34;
            this.m_Text4.Italic = true;
            this.m_Text4.Left = 427;
            this.m_Text4.MultiLine = true;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "SETUP";
            this.m_Text4.TextHorizontalAlignment = "Center";
            this.m_Text4.TextVerticalAlignment = "Center";
            this.m_Text4.Top = 233;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 48;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.Bold = true;
            this.m_Text7.DelayMouseInputPeriod = 0;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontFamily = "Arial";
            this.m_Text7.FontSizePixels = 20;
            this.m_Text7.Height = 34;
            this.m_Text7.Italic = true;
            this.m_Text7.Left = 522;
            this.m_Text7.MultiLine = true;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.ScreenOwnerName = "SETUP";
            this.m_Text7.TextHorizontalAlignment = "Center";
            this.m_Text7.TextVerticalAlignment = "Center";
            this.m_Text7.Top = 233;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 52;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 33;
            this.m_AnalogNumeric.Left = 435;
            this.m_AnalogNumeric.MaxValue = 100D;
            this.m_AnalogNumeric.MinValue = 50D;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric.Top = 290;
            this.m_AnalogNumeric.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric.ValidateValueOnInput = true;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 82;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric1.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 33;
            this.m_AnalogNumeric1.Left = 435;
            this.m_AnalogNumeric1.MaxValue = 100D;
            this.m_AnalogNumeric1.MinValue = 50D;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric1.Top = 333;
            this.m_AnalogNumeric1.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric1.ValidateValueOnInput = true;
            this.m_AnalogNumeric1.VisibleDynamicsValue = true;
            this.m_AnalogNumeric1.Width = 82;
            // 
            // m_AnalogNumeric2
            // 
            this.m_AnalogNumeric2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BlinkDynamicsValue = false;
            this.m_AnalogNumeric2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric2.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric2.EnabledDynamicsValue = true;
            this.m_AnalogNumeric2.FontSizePixels = 20;
            this.m_AnalogNumeric2.Height = 33;
            this.m_AnalogNumeric2.Left = 435;
            this.m_AnalogNumeric2.MaxValue = 100D;
            this.m_AnalogNumeric2.MinValue = 50D;
            this.m_AnalogNumeric2.Name = "m_AnalogNumeric2";
            this.m_AnalogNumeric2.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric2.Top = 380;
            this.m_AnalogNumeric2.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric2.ValidateValueOnInput = true;
            this.m_AnalogNumeric2.VisibleDynamicsValue = true;
            this.m_AnalogNumeric2.Width = 82;
            // 
            // m_AnalogNumeric3
            // 
            this.m_AnalogNumeric3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric3.BlinkDynamicsValue = false;
            this.m_AnalogNumeric3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric3.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric3.EnabledDynamicsValue = true;
            this.m_AnalogNumeric3.FontSizePixels = 20;
            this.m_AnalogNumeric3.Height = 33;
            this.m_AnalogNumeric3.Left = 435;
            this.m_AnalogNumeric3.MaxValue = 100D;
            this.m_AnalogNumeric3.MinValue = 50D;
            this.m_AnalogNumeric3.Name = "m_AnalogNumeric3";
            this.m_AnalogNumeric3.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric3.Top = 423;
            this.m_AnalogNumeric3.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric3.ValidateValueOnInput = true;
            this.m_AnalogNumeric3.VisibleDynamicsValue = true;
            this.m_AnalogNumeric3.Width = 82;
            // 
            // m_AnalogNumeric4
            // 
            this.m_AnalogNumeric4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric4.BlinkDynamicsValue = false;
            this.m_AnalogNumeric4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric4.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric4.EnabledDynamicsValue = true;
            this.m_AnalogNumeric4.FontSizePixels = 20;
            this.m_AnalogNumeric4.Height = 33;
            this.m_AnalogNumeric4.Left = 533;
            this.m_AnalogNumeric4.MaxValue = 100D;
            this.m_AnalogNumeric4.MinValue = 50D;
            this.m_AnalogNumeric4.Name = "m_AnalogNumeric4";
            this.m_AnalogNumeric4.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric4.Top = 290;
            this.m_AnalogNumeric4.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric4.ValidateValueOnInput = true;
            this.m_AnalogNumeric4.VisibleDynamicsValue = true;
            this.m_AnalogNumeric4.Width = 82;
            // 
            // m_AnalogNumeric5
            // 
            this.m_AnalogNumeric5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric5.BlinkDynamicsValue = false;
            this.m_AnalogNumeric5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric5.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric5.EnabledDynamicsValue = true;
            this.m_AnalogNumeric5.FontSizePixels = 20;
            this.m_AnalogNumeric5.Height = 33;
            this.m_AnalogNumeric5.Left = 533;
            this.m_AnalogNumeric5.MaxValue = 100D;
            this.m_AnalogNumeric5.MinValue = 50D;
            this.m_AnalogNumeric5.Name = "m_AnalogNumeric5";
            this.m_AnalogNumeric5.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric5.Top = 333;
            this.m_AnalogNumeric5.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric5.ValidateValueOnInput = true;
            this.m_AnalogNumeric5.VisibleDynamicsValue = true;
            this.m_AnalogNumeric5.Width = 82;
            // 
            // m_AnalogNumeric6
            // 
            this.m_AnalogNumeric6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric6.BlinkDynamicsValue = false;
            this.m_AnalogNumeric6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric6.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric6.EnabledDynamicsValue = true;
            this.m_AnalogNumeric6.FontSizePixels = 20;
            this.m_AnalogNumeric6.Height = 33;
            this.m_AnalogNumeric6.Left = 533;
            this.m_AnalogNumeric6.MaxValue = 100D;
            this.m_AnalogNumeric6.MinValue = 50D;
            this.m_AnalogNumeric6.Name = "m_AnalogNumeric6";
            this.m_AnalogNumeric6.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric6.Top = 380;
            this.m_AnalogNumeric6.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric6.ValidateValueOnInput = true;
            this.m_AnalogNumeric6.VisibleDynamicsValue = true;
            this.m_AnalogNumeric6.Width = 82;
            // 
            // m_AnalogNumeric7
            // 
            this.m_AnalogNumeric7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric7.BlinkDynamicsValue = false;
            this.m_AnalogNumeric7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric7.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric7.EnabledDynamicsValue = true;
            this.m_AnalogNumeric7.FontSizePixels = 20;
            this.m_AnalogNumeric7.Height = 33;
            this.m_AnalogNumeric7.Left = 533;
            this.m_AnalogNumeric7.MaxValue = 100D;
            this.m_AnalogNumeric7.MinValue = 50D;
            this.m_AnalogNumeric7.Name = "m_AnalogNumeric7";
            this.m_AnalogNumeric7.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric7.Top = 423;
            this.m_AnalogNumeric7.ValidateValueOnDisplay = true;
            this.m_AnalogNumeric7.ValidateValueOnInput = true;
            this.m_AnalogNumeric7.VisibleDynamicsValue = true;
            this.m_AnalogNumeric7.Width = 82;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontSizePixels = 15;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button4.Height = 56;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 631;
            this.m_Button4.MultiLine = true;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "SETUP";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button4.TextHeight = 36;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 110;
            this.m_Button4.Top = 231;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = -677441046;
            this.m_Button4.Width = 120;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.DelayMouseInputPeriod = 0;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontSizePixels = 20;
            this.m_Text9.Height = 21;
            this.m_Text9.Left = 602;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "SETUP";
            this.m_Text9.Top = 18;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 29;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontSizePixels = 15;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button2.Height = 58;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 631;
            this.m_Button2.MultiLine = true;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "SETUP";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button2.TextHeight = 36;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 110;
            this.m_Button2.Top = 402;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -2013161556;
            this.m_Button2.Width = 120;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.DelayMouseInputPeriod = 0;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "SETUP";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Line.StrokeThickness = 0;
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 138;
            this.m_Line.X2 = 504;
            this.m_Line.Y1 = 280;
            this.m_Line.Y2 = 280;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.DelayMouseInputPeriod = 0;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "SETUP";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 622;
            this.m_Line1.X2 = 256;
            this.m_Line1.Y1 = 286;
            this.m_Line1.Y2 = 286;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.DelayMouseInputPeriod = 0;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "SETUP";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 622;
            this.m_Line2.X2 = 256;
            this.m_Line2.Y1 = 325;
            this.m_Line2.Y2 = 325;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.DelayMouseInputPeriod = 0;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "SETUP";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 623;
            this.m_Line3.X2 = 257;
            this.m_Line3.Y1 = 374;
            this.m_Line3.Y2 = 374;
            // 
            // m_Line5
            // 
            this.m_Line5.BlinkDynamicsValue = false;
            this.m_Line5.DelayMouseInputPeriod = 0;
            this.m_Line5.EnabledDynamicsValue = true;
            this.m_Line5.Fill = null;
            this.m_Line5.Name = "m_Line5";
            this.m_Line5.ScreenOwnerName = "SETUP";
            this.m_Line5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line5.VisibleDynamicsValue = true;
            this.m_Line5.X1 = 257;
            this.m_Line5.X2 = 622;
            this.m_Line5.Y1 = 419;
            this.m_Line5.Y2 = 419;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.DelayMouseInputPeriod = 0;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "SETUP";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 422;
            this.m_Line4.X2 = 422;
            this.m_Line4.Y1 = 233;
            this.m_Line4.Y2 = 459;
            // 
            // m_Line6
            // 
            this.m_Line6.BlinkDynamicsValue = false;
            this.m_Line6.DelayMouseInputPeriod = 0;
            this.m_Line6.EnabledDynamicsValue = true;
            this.m_Line6.Fill = null;
            this.m_Line6.Name = "m_Line6";
            this.m_Line6.ScreenOwnerName = "SETUP";
            this.m_Line6.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line6.VisibleDynamicsValue = true;
            this.m_Line6.X1 = 525;
            this.m_Line6.X2 = 525;
            this.m_Line6.Y1 = 233;
            this.m_Line6.Y2 = 459;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button3.DelayMouseInputPeriod = 0;
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontSizePixels = 36;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button3.Height = 50;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 194;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "SETUP";
            this.m_Button3.StyleName = "Glossy";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button3.TextHeight = 43;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 371;
            this.m_Button3.Top = 8;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = -217591106;
            this.m_Button3.Width = 377;
            // 
            // m_SanPham
            // 
            this.m_SanPham.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SanPham.BlinkDynamicsValue = false;
            this.m_SanPham.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(143)))), ((int)(((byte)(164)))), ((int)(((byte)(190))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SanPham.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_SanPham.DelayMouseInputPeriod = 0;
            this.m_SanPham.EnabledDynamicsValue = true;
            this.m_SanPham.FontFamily = "Arial";
            this.m_SanPham.FontSizePixels = 24;
            this.m_SanPham.Height = 30;
            this.m_SanPham.Left = 404;
            this.m_SanPham.Name = "m_SanPham";
            this.m_SanPham.ReadOnly = true;
            this.m_SanPham.ScreenOwnerName = "SETUP";
            this.m_SanPham.TextHorizontalAlignment = "Center";
            this.m_SanPham.Top = 112;
            this.m_SanPham.VisibleDynamicsValue = true;
            this.m_SanPham.Width = 167;
            // 
            // m_MaSanPham
            // 
            this.m_MaSanPham.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_MaSanPham.BlinkDynamicsValue = false;
            this.m_MaSanPham.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(143)))), ((int)(((byte)(164)))), ((int)(((byte)(190))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_MaSanPham.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_MaSanPham.DelayMouseInputPeriod = 0;
            this.m_MaSanPham.EnabledDynamicsValue = true;
            this.m_MaSanPham.FontFamily = "Arial";
            this.m_MaSanPham.FontSizePixels = 24;
            this.m_MaSanPham.Height = 30;
            this.m_MaSanPham.Left = 404;
            this.m_MaSanPham.Name = "m_MaSanPham";
            this.m_MaSanPham.ReadOnly = true;
            this.m_MaSanPham.ScreenOwnerName = "SETUP";
            this.m_MaSanPham.TextHorizontalAlignment = "Center";
            this.m_MaSanPham.Top = 155;
            this.m_MaSanPham.VisibleDynamicsValue = true;
            this.m_MaSanPham.Width = 167;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button5.DelayMouseInputPeriod = 0;
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontSizePixels = 15;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button5.Height = 58;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 631;
            this.m_Button5.MultiLine = true;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "SETUP";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button5.TextHeight = 36;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 110;
            this.m_Button5.Top = 286;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -2013161556;
            this.m_Button5.Width = 120;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "Arial";
            this.m_Button1.FontSizePixels = 15;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 58;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 631;
            this.m_Button1.MultiLine = true;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "SETUP";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button1.TextHeight = 34;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 110;
            this.m_Button1.Top = 344;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -2013161556;
            this.m_Button1.Width = 120;
            // 
            // m_Button6
            // 
            this.m_Button6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(150)))), ((int)(((byte)(70))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button6.DelayMouseInputPeriod = 0;
            this.m_Button6.EnabledDynamicsValue = true;
            this.m_Button6.FontSizePixels = 36;
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button6.Height = 50;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 194;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "SETUP";
            this.m_Button6.StyleName = "Glossy";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button6.TextHeight = 43;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 371;
            this.m_Button6.Top = -50;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = -217591106;
            this.m_Button6.Width = 377;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Arial";
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 34;
            this.m_Text.Italic = true;
            this.m_Text.Left = 69;
            this.m_Text.MultiLine = true;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "SETUP";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 232;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 83;
            // 
            // m_Line7
            // 
            this.m_Line7.BlinkDynamicsValue = false;
            this.m_Line7.DelayMouseInputPeriod = 0;
            this.m_Line7.EnabledDynamicsValue = true;
            this.m_Line7.Fill = null;
            this.m_Line7.Name = "m_Line7";
            this.m_Line7.ScreenOwnerName = "SETUP";
            this.m_Line7.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line7.StrokeThickness = 2;
            this.m_Line7.VisibleDynamicsValue = true;
            this.m_Line7.X1 = 241;
            this.m_Line7.X2 = 48;
            this.m_Line7.Y1 = 285;
            this.m_Line7.Y2 = 285;
            // 
            // m_AnalogNumeric8
            // 
            this.m_AnalogNumeric8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric8.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric8.BlinkDynamicsValue = false;
            this.m_AnalogNumeric8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric8.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric8.EnabledDynamicsValue = true;
            this.m_AnalogNumeric8.FontSizePixels = 40;
            this.m_AnalogNumeric8.Height = 103;
            this.m_AnalogNumeric8.Left = 78;
            this.m_AnalogNumeric8.Name = "m_AnalogNumeric8";
            this.m_AnalogNumeric8.ScreenOwnerName = "SETUP";
            this.m_AnalogNumeric8.Top = 323;
            this.m_AnalogNumeric8.VisibleDynamicsValue = true;
            this.m_AnalogNumeric8.Width = 136;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "SETUP";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_SETUP = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_SETUP) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Text14);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric3);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric4);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric5);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric6);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric7);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Line5);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_Line6);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_SanPham);
            this.DrawingPrimitives.Add(this.m_MaSanPham);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Line7);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric8);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_SanPham)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MaSanPham)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric8)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
        }
        
        private void m_AnalogNumeric_Action_GotFocus(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.Tags.tram_han_tren.SetAnalog(1);
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Load);
            if (string.IsNullOrEmpty(recipeFieldName)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.Recipe1.LoadRecipe(recipeFieldName);
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Delete);
            if (string.IsNullOrEmpty(recipeFieldName)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.Recipe1.DeleteRecipe(recipeFieldName);
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Save);
            if (string.IsNullOrEmpty(recipeFieldName)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.Recipe1.SaveRecipe(recipeFieldName);
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "SETUP2", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.SETUP2.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(SETUP));
            this.m_Button.Text = resources.GetText("SETUP.Button.Text", "Trở lại");
            this.m_Text1.Text = resources.GetText("SETUP.Text1.Text", "Tên Sản phẩm:");
            this.m_Text2.Text = resources.GetText("SETUP.Text2.Text", "Mã Sản phẩm:");
            this.m_Text5.Text = resources.GetText("SETUP.Text5.Text", "Trạm hàn trên");
            this.m_Text6.Text = resources.GetText("SETUP.Text6.Text", "Trạm hàn dưới");
            this.m_Text8.Text = resources.GetText("SETUP.Text8.Text", "Trạm hàn số lô");
            this.m_Text13.Text = resources.GetText("SETUP.Text13.Text", "Trạm hàn Seal");
            this.m_Text14.Text = resources.GetText("SETUP.Text14.Text", "Trạm hàn");
            this.m_Text7.Text = resources.GetText("SETUP.Text7.Text", "Nhiệt độ \r\ncảnh báo");
            this.m_Button4.Text = resources.GetText("SETUP.Button4.Text", "CHỌN \r\nSẢN PHẨM");
            this.m_Text9.Text = resources.GetText("SETUP.Text9.Text", "User");
            this.m_Text4.Text = resources.GetText("SETUP.Text4.Text", "Nhiệt độ \r\ncài đặt");
            this.m_Button2.Text = resources.GetText("SETUP.Button2.Text", "XÓA \r\nSẢN PHẨM");
            this.m_Button3.Text = resources.GetText("SETUP.Button3.Text", "CÀI ĐẶT THÔNG SỐ");
            this.m_SanPham.Text = resources.GetText("SETUP.SanPham.Text", "San Pham");
            this.m_MaSanPham.Text = resources.GetText("SETUP.MaSanPham.Text", "Ma San Pham");
            this.m_Button5.Text = resources.GetText("SETUP.Button5.Text", "LƯU \r\nTHAY ĐỔI");
            this.m_Button1.Text = resources.GetText("SETUP.Button1.Text", "SẢN PHẨM\r\nMỚI");
            this.m_Button6.Text = resources.GetText("SETUP.Button6.Text", "CÀI ĐẶT THÔNG SỐ");
            this.m_Text.Text = resources.GetText("SETUP.Text.Text", "Độ dài \r\nbước kéo (mm)");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_SETUP) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tram_han_tren"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanduoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSeal"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric2.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tramhanSolo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric3.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Canhbaotren"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric4.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Canhbaoduoi"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric5.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CanhbaoSeal"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric6.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.CanhbaoSolo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric7.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text9.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_DoDaiBuocKeo"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric8.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
        }
    }
}
