//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem tram_han_tren;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem tramhanduoi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem tramhanSeal;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem tramhanSolo;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Tensanpham;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Masanpham;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagLatestLoadedRecipeName;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Canhbaotren;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Canhbaoduoi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem CanhbaoSeal;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem CanhbaoSolo;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagDateTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag sosanpham;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Solosanpham;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag nhiethantrenhientai;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag nhiethanduoihientai;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag nhiethansealhientai;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag nhiethansolohientai;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag tanso;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag nhipcat;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Nhiettren;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Nhietduoi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag NhietSeal;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag NhietSoLo;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem TenThietbi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Modelthietbi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Mathietbi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag TongSovi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SoViLoi;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MaSanPham1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem TrangThaiHeThong;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_DoDaiBuocKeo;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_NgaySX;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCurrentUser;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.tram_han_tren = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("tram_han_tren", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.tramhanduoi = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("tramhanduoi", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.tramhanSeal = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("tramhanSeal", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.tramhanSolo = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("tramhanSolo", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Tensanpham = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Tensanpham", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), "", ((short)(1)), "", "");
			this.Masanpham = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Masanpham", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), "", ((short)(1)), "", "");
			this.SystemTagLatestLoadedRecipeName = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Latest Loaded Recipe Name", "SystemTagLatestLoadedRecipeName", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Name of the latest loaded recipe", ((short)(1)), "", "");
			this.Canhbaotren = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Canhbaotren", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Canhbaoduoi = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Canhbaoduoi", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.CanhbaoSeal = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("CanhbaoSeal", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.CanhbaoSolo = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("CanhbaoSolo", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.SystemTagDateTime = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("DateTime", "SystemTagDateTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Current date and time", ((short)(1)), "", "");
			this.sosanpham = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("sosanpham", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Solosanpham = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Solosanpham", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.nhiethantrenhientai = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("nhiethantrenhientai", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.nhiethanduoihientai = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("nhiethanduoihientai", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.nhiethansealhientai = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("nhiethansealhientai", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.nhiethansolohientai = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("nhiethansolohientai", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.tanso = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("tanso", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.nhipcat = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("nhipcat", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Nhiettren = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Nhiettren", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Nhietduoi = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Nhietduoi", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.NhietSeal = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("NhietSeal", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.NhietSoLo = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("NhietSoLo", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.TenThietbi = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("TenThietbi", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Modelthietbi = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Modelthietbi", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.Mathietbi = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Mathietbi", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.TongSovi = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("TongSovi", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.SoViLoi = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SoViLoi", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.MaSanPham1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MaSanPham1", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.TrangThaiHeThong = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("TrangThaiHeThong", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_UINTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), "", ((short)(1)), "", "");
			this.HMI_DoDaiBuocKeo = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_DoDaiBuocKeo", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.HMI_NgaySX = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_NgaySX", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), false, "", null);
			this.SystemTagCurrentUser = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Current User", "SystemTagCurrentUser", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "The username of the currently logged in user", ((short)(1)), "", "");
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.tram_han_tren.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.tram_han_tren.SynchId = 45;
			this.tramhanduoi.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.tramhanduoi.SynchId = 46;
			this.tramhanSeal.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.tramhanSeal.SynchId = 47;
			this.tramhanSolo.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.tramhanSolo.SynchId = 48;
			this.Tensanpham.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Tensanpham.SynchId = 49;
			this.Masanpham.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Masanpham.SynchId = 50;
			this.SystemTagLatestLoadedRecipeName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.SystemTagLatestLoadedRecipeName.SynchId = 51;
			this.SystemTagLatestLoadedRecipeName.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.SystemTagLatestLoadedRecipeName_ValueChange);
			this.Canhbaotren.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Canhbaotren.SynchId = 55;
			this.Canhbaoduoi.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Canhbaoduoi.SynchId = 56;
			this.CanhbaoSeal.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.CanhbaoSeal.SynchId = 57;
			this.CanhbaoSolo.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.CanhbaoSolo.SynchId = 58;
			this.SystemTagDateTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("10/1/2018 3:40:32 PM"), 0, new string[0], new string[0], true));
			this.SystemTagDateTime.SynchId = 59;
			this.sosanpham.SynchId = 60;
			this.Solosanpham.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Solosanpham.SynchId = 61;
			this.nhiethantrenhientai.SynchId = 62;
			this.nhiethanduoihientai.SynchId = 63;
			this.nhiethansealhientai.SynchId = 64;
			this.nhiethansolohientai.SynchId = 65;
			this.tanso.SynchId = 66;
			this.nhipcat.SynchId = 67;
			this.Nhiettren.SynchId = 68;
			this.Nhietduoi.SynchId = 69;
			this.NhietSeal.SynchId = 70;
			this.NhietSoLo.SynchId = 71;
			this.TenThietbi.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.TenThietbi.SynchId = 72;
			this.Modelthietbi.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Modelthietbi.SynchId = 73;
			this.Mathietbi.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Mathietbi.SynchId = 74;
			this.TongSovi.SynchId = 75;
			this.SoViLoi.SynchId = 76;
			this.MaSanPham1.SynchId = 77;
			this.TrangThaiHeThong.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.TrangThaiHeThong.SynchId = 78;
			this.HMI_DoDaiBuocKeo.SynchId = 79;
			this.HMI_NgaySX.SynchId = 80;
			this.SystemTagCurrentUser.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.SystemTagCurrentUser.SynchId = 82;
			this.GlobalDataItems.Add(this.tram_han_tren);
			this.GlobalDataItems.Add(this.tramhanduoi);
			this.GlobalDataItems.Add(this.tramhanSeal);
			this.GlobalDataItems.Add(this.tramhanSolo);
			this.GlobalDataItems.Add(this.Tensanpham);
			this.GlobalDataItems.Add(this.Masanpham);
			this.GlobalDataItems.Add(this.SystemTagLatestLoadedRecipeName);
			this.GlobalDataItems.Add(this.Canhbaotren);
			this.GlobalDataItems.Add(this.Canhbaoduoi);
			this.GlobalDataItems.Add(this.CanhbaoSeal);
			this.GlobalDataItems.Add(this.CanhbaoSolo);
			this.GlobalDataItems.Add(this.SystemTagDateTime);
			this.LightweightTags.Add(this.sosanpham);
			this.GlobalDataItems.Add(this.Solosanpham);
			this.LightweightTags.Add(this.nhiethantrenhientai);
			this.LightweightTags.Add(this.nhiethanduoihientai);
			this.LightweightTags.Add(this.nhiethansealhientai);
			this.LightweightTags.Add(this.nhiethansolohientai);
			this.LightweightTags.Add(this.tanso);
			this.LightweightTags.Add(this.nhipcat);
			this.LightweightTags.Add(this.Nhiettren);
			this.LightweightTags.Add(this.Nhietduoi);
			this.LightweightTags.Add(this.NhietSeal);
			this.LightweightTags.Add(this.NhietSoLo);
			this.GlobalDataItems.Add(this.TenThietbi);
			this.GlobalDataItems.Add(this.Modelthietbi);
			this.GlobalDataItems.Add(this.Mathietbi);
			this.LightweightTags.Add(this.TongSovi);
			this.LightweightTags.Add(this.SoViLoi);
			this.LightweightTags.Add(this.MaSanPham1);
			this.GlobalDataItems.Add(this.TrangThaiHeThong);
			this.LightweightTags.Add(this.HMI_DoDaiBuocKeo);
			this.LightweightTags.Add(this.HMI_NgaySX);
			this.GlobalDataItems.Add(this.SystemTagCurrentUser);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
			this.ServerInfo += new System.EventHandler<Neo.ApplicationFramework.Interfaces.Events.ServerInfoArgs>(this.Tags_ServerInfo);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class GlobalDataItemExposure : Neo.ApplicationFramework.Interfaces.ITagExposure
	{
		
		public bool GetTagExposure(Neo.ApplicationFramework.Interfaces.Tag.IBasicTag dataItem)
		{
			return true;
		}
	}
}
