//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class TextLibrary : Neo.ApplicationFramework.Tools.MessageLibrary.MessageLibrary, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.MessageLibrary.MessageGroup m_MÃ_SẢN_PHẨM;
		
		private Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem m_MÃ_SẢN_PHẨM_MessageItem0;
		
		private Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem m_MÃ_SẢN_PHẨM_MessageItem1;
		
		private Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem m_MÃ_SẢN_PHẨM_MessageItem2;
		
		public TextLibrary()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.MessageLibrary.MessageGroup MÃ_SẢN_PHẨM
		{
			get
			{
				return this.m_MÃ_SẢN_PHẨM;
			}
			set
			{
				this.m_MÃ_SẢN_PHẨM = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem MÃ_SẢN_PHẨM_MessageItem0
		{
			get
			{
				return this.m_MÃ_SẢN_PHẨM_MessageItem0;
			}
			set
			{
				this.m_MÃ_SẢN_PHẨM_MessageItem0 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem MÃ_SẢN_PHẨM_MessageItem1
		{
			get
			{
				return this.m_MÃ_SẢN_PHẨM_MessageItem1;
			}
			set
			{
				this.m_MÃ_SẢN_PHẨM_MessageItem1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem MÃ_SẢN_PHẨM_MessageItem2
		{
			get
			{
				return this.m_MÃ_SẢN_PHẨM_MessageItem2;
			}
			set
			{
				this.m_MÃ_SẢN_PHẨM_MessageItem2 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.MÃ_SẢN_PHẨM = new Neo.ApplicationFramework.Tools.MessageLibrary.MessageGroup();
			this.MÃ_SẢN_PHẨM_MessageItem0 = new Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem();
			this.MÃ_SẢN_PHẨM_MessageItem1 = new Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem();
			this.MÃ_SẢN_PHẨM_MessageItem2 = new Neo.ApplicationFramework.Tools.MessageLibrary.MessageItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem2)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.MÃ_SẢN_PHẨM_MessageItem2)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.MÃ_SẢN_PHẨM_MessageItem0.DisplayName = "MessageItem0";
			this.MÃ_SẢN_PHẨM_MessageItem0.EndValue = 0;
			this.MÃ_SẢN_PHẨM_MessageItem0.GroupName = "MÃ_SẢN_PHẨM";
			this.MÃ_SẢN_PHẨM_MessageItem0.Name = "MÃ_SẢN_PHẨM_MessageItem0";
			this.MÃ_SẢN_PHẨM_MessageItem0.StartValue = 0;
			this.MÃ_SẢN_PHẨM_MessageItem1.DisplayName = "MessageItem1";
			this.MÃ_SẢN_PHẨM_MessageItem1.EndValue = 1;
			this.MÃ_SẢN_PHẨM_MessageItem1.GroupName = "MÃ_SẢN_PHẨM";
			this.MÃ_SẢN_PHẨM_MessageItem1.Name = "MÃ_SẢN_PHẨM_MessageItem1";
			this.MÃ_SẢN_PHẨM_MessageItem1.StartValue = 1;
			this.MÃ_SẢN_PHẨM_MessageItem2.DisplayName = "MessageItem2";
			this.MÃ_SẢN_PHẨM_MessageItem2.EndValue = 2;
			this.MÃ_SẢN_PHẨM_MessageItem2.GroupName = "MÃ_SẢN_PHẨM";
			this.MÃ_SẢN_PHẨM_MessageItem2.Name = "MÃ_SẢN_PHẨM_MessageItem2";
			this.MÃ_SẢN_PHẨM_MessageItem2.StartValue = 2;
			this.MÃ_SẢN_PHẨM.Messages.Add(this.MÃ_SẢN_PHẨM_MessageItem0);
			this.MÃ_SẢN_PHẨM.Messages.Add(this.MÃ_SẢN_PHẨM_MessageItem1);
			this.MÃ_SẢN_PHẨM.Messages.Add(this.MÃ_SẢN_PHẨM_MessageItem2);
			this.MÃ_SẢN_PHẨM.Name = "MÃ_SẢN_PHẨM";
			this.Groups.Add(this.MÃ_SẢN_PHẨM);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(TextLibrary));
			this.m_MÃ_SẢN_PHẨM_MessageItem0.Message = resources.GetText("TextLibrary.MÃ_SẢN_PHẨM_MessageItem0.Message", "AAA");
			this.m_MÃ_SẢN_PHẨM_MessageItem1.Message = resources.GetText("TextLibrary.MÃ_SẢN_PHẨM_MessageItem1.Message", "BBB");
			this.m_MÃ_SẢN_PHẨM_MessageItem2.Message = resources.GetText("TextLibrary.MÃ_SẢN_PHẨM_MessageItem2.Message", "CCC");
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
